### PR TITLE
[feat] legacy SBI call compatibility

### PR DESCRIPTION
**Pull request by hky1999**

### CODE REVIEW

**Comment by hky1999** [comment]
I also resolved cargo doc error through `#[doc(hidden)]` and some more comments @aarkegz

**Review by aarkegz — APPROVED** [review]
GJ

**Comment by pengzechen** [comment]
Emm. I'm not familiar with RISC-V; if it were ARM64 or x86, I might be able to provide some reference or suggestions.

**Comment by hky1999** [comment]
> Emm. I'm not familiar with RISC-V; if it were ARM64 or x86, I might be able to provide some reference or suggestions.

merged, thx

**Pull request merged**
